;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "emacs-ztree"
        "emacs-forge"
        "emacs-helpful"
        "emacs-elisp-refs"
        "emacs-magit-todos"
        "emacs-perspective@2.16-7-20230114"
        "emacs-crux"
        "emacs-elfeed"
        "emacs-detached"
        "glibc-locales"
        "direnv"
        "dropbear"
        "dtach"
        "emacs-ace-window"
        "emacs-anzu"
        "emacs-avy"
        "emacs-beacon"
        "emacs-cape"
        "emacs-consult@0.31-20230116"
        "emacs-corfu"
        "emacs-corfu-terminal"
        "emacs-diredfl"
        "emacs-dumb-jump"
        "emacs-embark"
        "emacs-embark-consult"
        "emacs-envrc"
        "emacs-expand-region"
        "emacs-geiser"
        "emacs-geiser-guile"
        "emacs-git-gutter"
        "emacs-guix"
        "emacs-hl-todo"
        "emacs-magit"
        "emacs-marginalia"
        "emacs-move-text"
        "emacs-multiple-cursors"
        "emacs-next"
        "emacs-orderless"
        "emacs-pinentry"
        "emacs-project"
        "emacs-rainbow-delimiters"
        "emacs-rainbow-mode"
        "emacs-rg"
        "emacs-shell-command+"
        "emacs-smartparens"
        "emacs-symbol-overlay"
        "emacs-transient"
        "emacs-use-package"
        "emacs-vertico"
        "emacs-volatile-highlights"
        "emacs-vterm"
        "emacs-vundo"
        "emacs-yasnippet"
        "emacs-consult-yasnippet"
        "git-crypt"
        "global"
        "guile"
        "ripgrep"
        "rsync"
        "socat"
        "tmate"
        "zip"))
