;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "emacs-next-nox"
        "emacs-ace-window"
        "emacs-anzu"
        "emacs-avy"
        "emacs-beacon"
        "emacs-cape"
        "emacs-codespaces"
        "emacs-combobulate"
        "emacs-consult"
        "emacs-consult-yasnippet"
        "emacs-corfu"
        "emacs-corfu-terminal"
        "emacs-crux"
        "emacs-detached"
        "emacs-diredfl"
        "emacs-dumb-jump"
        "emacs-eev"
        "emacs-elfeed"
        "emacs-elpa-mirror"
        "emacs-embark-consult"
        "emacs-embark@0.22.1.20230427"
        "emacs-engine-mode"
        "emacs-envrc"
        "emacs-expreg"
        "emacs-forge"
        "emacs-gcmh"
        "emacs-geiser"
        "emacs-geiser-guile"
        "emacs-gist"
        "emacs-git-gutter"
        "emacs-guix"
        "emacs-helpful"
        "emacs-hl-todo"
        "emacs-inspector"
        "emacs-isearch-mb"
        "emacs-magit"
        "emacs-magit-todos"
        "emacs-marginalia"
        "emacs-move-text"
        "emacs-multiple-cursors"
        "emacs-ob-compile"
        "emacs-orderless"
        "emacs-org-alert"
        "emacs-org-bullets"
        "emacs-pcmpl-args"
        "emacs-perspective@2.16.20230114"
        "emacs-pinentry"
        "emacs-project"
        "emacs-project-tasks"
        "emacs-rainbow-delimiters"
        "emacs-rainbow-mode"
        "emacs-rg"
        "emacs-shell-command+"
        "emacs-smartparens"
        "emacs-symbol-overlay"
        "emacs-vertico"
        "emacs-volatile-highlights"
        "emacs-vterm"
        "emacs-vundo"
        "emacs-xclip"
        "emacs-yaml-mode"
        "emacs-yasnippet"
        "emacs-yasnippet-snippets"
        "emacs-ztree"
        ;; dotfiles
        "oops-next"
        ;; libs
        "tree-sitter"
        "tree-sitter-bash"
        "tree-sitter-c"
        "tree-sitter-cli"
        "tree-sitter-clojure"
        "tree-sitter-cpp"
        "tree-sitter-css"
        "tree-sitter-go"
        "tree-sitter-haskell"
        "tree-sitter-html"
        "tree-sitter-java"
        "tree-sitter-javascript"
        "tree-sitter-json"
        "tree-sitter-markdown"
        "tree-sitter-org"
        "tree-sitter-php"
        "tree-sitter-python"
        "tree-sitter-ruby"
        "tree-sitter-rust"
        "tree-sitter-scheme"
        "tree-sitter-typescript"
        ;; tools
        "direnv"
        "dtach"
        "jq"
        "ripgrep"
        "rsync"
        "socat"))
