---
name: Check dotfiles
on:
  schedule:
    - cron:  '30 23 */7 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      with:
        token: ${{ secrets.TOKEN }}
      uses: actions/checkout@v2

    - name: Check dots version
      run: |
        SHA=$(curl https://api.github.com/repos/txgvnn/dots/commits/master | jq -r '.sha')
        TAG="v$(date +%Y%m%d)"
        echo "SHA=$SHA, TAG=$TAG"
        sed -i 's,DOTS_VERSION=.*,DOTS_VERSION='"$SHA"',' Dockerfile
        git config user.name github-actions
        git config user.email github-actions@github.com
        git diff
        git add -u
        ret=$(git commit -m "$TAG release" 1>&2; echo $?)
        if [ $ret -eq 0 ]; then
          git push origin main
          git tag "$TAG"
          git push origin "$TAG"
        fi
