name: Build pack
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: true
    - name: Guix cache
      if: ${{ ! steps.guix_pack_cache.outputs.cache-hit }}
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/guix
        key: guix-cache
        restore-keys: |
          guix-cache
    - name: Install Guix
      id: install-guix
      uses: TxGVNN/guix-install-action@v1
      with:
        channels: |-
            (list (channel
                   (name 'guix)
                   (url "https://git.savannah.gnu.org/git/guix.git"))
                  (channel
                   (name 'guxti)
                   (url "https://github.com/TxGVNN/guxti")))
    - name: Get and build packages
      shell: bash
      run: |
        mkdir packages
        wget -O - https://txgvnn.github.io/guxti/signing-key.pub | sudo guix archive --authorize
        guix pack -L ./ -f tarball -C xz --root=packages/guix.tar.xz -m guix-install.d/pack.scm --substitute-urls="https://ci.guix.gnu.org https://bordeaux.guix.gnu.org https://txgvnn.github.io/guxti"

    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'packages'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
