name: Build pack
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: true
    - name: Guix cache
      if: ${{ ! steps.guix_pack_cache.outputs.cache-hit }}
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/guix
        key: guix-cache
        restore-keys: |
          guix-cache
    - name: Install Guix
      id: install-guix
      uses: TxGVNN/guix-install-action@v1
      with:
        channels: |-
            (list (channel
                   (name 'guxti)
                   (branch "update-guix")
                   (url "https://github.com/TxGVNN/guxti")
                   (introduction
                    (make-channel-introduction
                     "34ce27aeadde4ab8b26802453628f713155c0e96"
                     (openpgp-fingerprint
                      "97EE 7685 F353 F3BB AAFC  D3DA 8D6C 190A CBFE 117C"))))
                  (channel
                   (name 'guix)
                   (branch "emacs-team")
                   (commit "0a50703abd5bfb27c7e130644db3045032604751")
                   (url "https://codeberg.org/guix/guix.git")
                   (introduction
                    (make-channel-introduction
                     "9edb3f66fd807b096b48283debdcddccfea34bad"
                     (openpgp-fingerprint
                      "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))
    - name: Get and build packages
      shell: bash
      run: |
        mkdir -p packages
        wget -O - https://txgvnn.github.io/guxti/signing-key.pub | sudo guix archive --authorize
        guix package -m guix-install.d/manifest.scm
        guix pack -L ./ -f tarball -C xz --root=packages/guix.tar.xz -m guix-install.d/pack.scm --substitute-urls="https://cache-cdn.guix.moe https://ci.guix.gnu.org https://bordeaux.guix.gnu.org"
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'packages'

  # Deploy job
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
